### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ms3056** [ozntel/oz-calendar#10]
Getting this error when I enable the plugin:

```loag
plugin:oz-calendar:7902 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'openViewOnStart')
    at eval (plugin:oz-calendar:7902:44)
    at e.addToggle (app.js:1:817831)
    at OZCalendarPluginSettingsTab.display (plugin:oz-calendar:7901:176)
    at SettingsSearch.getTabResources (plugin:settings-search:228:15)
    at t.eval (plugin:settings-search:264:16)
    at t.wrapper [as addSettingTab] (plugin:settings-search:59:20)
    at t.addSettingTab (app.js:1:1946054)
    at OZCalendarPlugin.onload (plugin:oz-calendar:8287:10)
    at e.load (app.js:1:631148)
    at e.<anonymous> (app.js:1:1952893)
    ```

**Comment by ozntel** [comment]
Does this problem still happen? I have tested on all different platforms but it doesn't happen at all. I will also need more details which platform you are using, which version of Obsidian you are using, which version of plugin you are trying to install etc.

**Comment by ms3056** [comment]
I am no longer seeing this error. Perhaps something I was doing in my snippets was causing a conflict.
